### list sessions
GET http://localhost:12345/rest/sessions
Accept: application/json

### list session urls
GET http://localhost:12345/rest/session/test-1/urls
Accept: application/json

### list files

GET http://localhost:12345/rest/files
Accept: application/json

### list session files

GET http://localhost:12345/rest/files/test-2
Accept: application/json

### get downloaded file

GET http://localhost:12345/rest/file/session-1/138b5e36ab1f20a4c32298cf02b6304f?filter=Test-Filter
Accept: application/json

### diff 2 downloaded files

GET http://localhost:12345/rest/diff/test-1/test-request-1/test-2/test-request-1
Accept: application/json

### filters list
GET http://localhost:12345/rest/filters
Accept: application/json

### add/update new filter
POST http://localhost:12345/rest/filter
Accept: application/json

{
"name":"Test-Filter2",
"filter":"a filter...1"
}

### delete new filter
DELETE http://localhost:12345/rest/filter/Test-Filter2


### enqueue download

POST http://localhost:12345/rest/download
Accept: application/json

{
"id":"test-request-1",
"url":"http://localhost:2222/index-1.html",
"session":"test-1"
}

### enqueue download

POST http://localhost:12345/rest/download
Accept: application/json

{
"id":"test-request-1",
"url":"http://localhost:2222/index-2.html",
"session":"test-2"
}

### enqueue download

POST http://localhost:12345/rest/download
Accept: application/json

{
"id":"test-request-2",
"url":"http://localhost:2222/index-1.html",
"session":"test-1"
}

### enqueue download

POST http://localhost:12345/rest/download
Accept: application/json

{
"id":"test-request-2",
"url":"http://localhost:2222/index-3.html",
"session":"test-2"
}


### index.html

GET http://localhost:12345/webapp
Accept: application/json

### asset
GET http://localhost:12345/webapp/assets/css/app.css
Accept: application/json
