Version = "1"

[[command]]
name = "some-nginx"
image = "nginx"
removeContainer = true
isDetached = true
volumes = [
    "${HOME}/go/src/github.com/Oppodelldog/webdiff/.droxy/testfiles:/usr/share/nginx/html"
]
ports = [
    "2222:80"
]
